export const COLORS = [
    { nombre: 'Azul claro', valor: '#add8e6' },
    { nombre: 'Verde menta', valor: '#98fb98' },
    { nombre: 'Gris perla', valor: '#eaeaea' },
    { nombre: 'Lavanda', valor: '#e6e6fa' },
    { nombre: 'Rosa suave', valor: '#ffb6c1' },
    { nombre: 'Beige', valor: '#f5f5dc' },
    { nombre: 'Amarillo pálido', valor: '#fffacd' },
    { nombre: 'Gris azulado', valor: '#A7C2D9' },
    { nombre: 'Azul claro 2', valor: '#87CEEB' },
    { nombre: 'Verde claro', valor: '#98FB98' },
    { nombre: 'Amarillo suave', valor: '#FFFF99' },
    { nombre: 'Rosa pastel', valor: '#FFD1DC' },
    { nombre: 'Naranja claro', valor: '#FFD700' },
    { nombre: 'Morado suave', valor: '#D8BFD8' },
    { nombre: 'Verde menta', valor: '#00FF7F' },
    { nombre: 'Gris plateado', valor: '#C0C0C0' },
    { nombre: 'Melocotón', valor: '#FFDAB9' },
    { nombre: 'Azul cielo', valor: '#87CEEB' },
    { nombre: 'Lavanda', valor: '#E6E6FA' },
    { nombre: 'Amarillo pálido', valor: '#FFFACD' },
    { nombre: 'Coral suave', valor: '#FF8474' },
    { nombre: 'Verde agua', valor: '#00FFFF' },
    { nombre: 'Gris perla', valor: '#EAEAEA' }
  ];